# Importar Modulos

In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import plotly.express as px
import tensorflow as tf

from matplotlib import pyplot as plt
from sklearn import preprocessing
from IPython.display import display

# Importación de Datos

In [13]:
data = np.loadtxt("lp5.csv", delimiter=",", dtype=str)
data_copy = data #va de 0 a 2623 o sea 2624 datos
cont = 16
labels = []
features = []
uf= np.zeros((164,15,6))

for i in range(len(data_copy)):
    if(cont == 16):
        labels.append(data_copy[i])
    if(cont<16):
        features.append(data_copy[i])
    cont -= 1
    if(cont == 0):
        cont = 16
        
cont = 0
for i in range(164):
    for j in range(15):
        for z in range(6):
            uf[i][j][z] = features[cont][z]
        cont += 1
        
labels_df = pd.DataFrame(labels)
features_df = pd.DataFrame(features)
display(labels_df)
display(features_df)

[[[ -2.  -1.  81.   0.  -5.   0.]
  [ -2.  -1.  79.   0.  -4.   0.]
  [ -2.  -1.  79.   0.  -4.   0.]
  ...
  [ -2.  -1.  78.   0.  -5.   0.]
  [ -3.  -1.  80.   1.  -4.   1.]
  [ -2.  -1.  79.   0.  -4.   0.]]

 [[  6.  -1.  79.  -2.   4.  -3.]
  [ 42.  -3.  80.   5.  53.   3.]
  [ -5.   4.  74. -15. -10.  -1.]
  ...
  [ -1.  -5.  80.   6.  -6.   0.]
  [ -4.   5.  78. -14.  -9.  -4.]
  [ -4.   1.  80.  -3. -12.   5.]]

 [[ -2.  -6.  85.  14.  -5.   2.]
  [  0.   2.  74.  -7.   1.   0.]
  [ -4.  -5.  76.   7. -11.   4.]
  ...
  [  0.  -9.  87.  13.  -5.   2.]
  [ -5.   5.  67. -17. -16.   7.]
  [ -6. -10.  86.  16. -14.  -1.]]

 ...

 [[-12.  17.   3. -19. -10.  -4.]
  [-12.  12.  11. -13. -16.  -4.]
  [ -8.   3.   6.   2. -11.  -4.]
  ...
  [  0.   1.   3.   1.   1.  -3.]
  [  1.   2.   9.   0.   3.  -4.]
  [  1.   2.   9.   0.   3.  -4.]]

 [[-41.  21.  -5. -23. -59.  -4.]
  [-32.  21.  -6. -25. -45.  -4.]
  [-21.  12.  -6. -14. -31.  -4.]
  ...
  [ -4.   4.   3.   0.  -1.  -3.]
  [ 

0 1  2  3  4  5 
0               normal               
1               normal               
2               normal               
3               normal               
4               normal               
..                 ... .. .. .. .. ..
159  collision_in_tool               
160  collision_in_tool               
161  collision_in_tool               
162  collision_in_tool               
163  collision_in_tool               

[164 rows x 6 columns]

0   1   2   3   4   5
0     -2  -1  81   0  -5   0
1     -2  -1  79   0  -4   0
2     -2  -1  79   0  -4   0
3     -2  -1  80   0  -4   0
4     -3  -1  79   1  -5   1
...   ..  ..  ..  ..  ..  ..
2455   1   1   8   0   3  -4
2456   0   0   5   0   3  -4
2457  -1   1  -3  -3  -2  -3
2458   0  -1  -5  -1   1  -3
2459  -1   1   4   0  -1  -3

[2460 rows x 6 columns]